server:
  port: 8082

spring:
  datasource:
    url: '{cipher}AQBsdAHTmFuw89p8SsQ4INNHaE5gyG4Ra8fCNcq+4J0EUoCFXrGr9ZCP1NyVB290nNSSiT0LZp1ghcN4khedfEKdt+KYqYm0GGmrsfxhnpPhfJwdBQO32mH+1xBO/tSIHgfzVpfmIu/aHkkZ0tGYGFXVm/rg1qAVRxPhi46mJ7YGVTfbaFgRJg9haZYCbMEeyg1K8yx1WTzsDYwVUPJ/B0rTa93/RQ9nzJDWUhz/mRs87EYc2btKDd0BDqHkt9sYqfDatkkMWei1gLk7BPQuOSIEZmD6Fj8K1eL9G5BmYWYDXqbE/ZfS4BNgiW1H3c+uc0hobeYBUQr3w3F1mWBOUAqnsGrIAiI5TGfAX5vOqNfZuqFMELeljV8yzVyZIcIhc+aPyx5e9/eW1TkPs1bHw4pC04zXmRARj1iYfM6m2YLRQ2To7OJJftaIuZI9jMAalhw='
file:
  storage:
    enabled: true
    bucketName: '{cipher}AQCG8+0RR3/N9KZFBxwvLFWGJUbl3bTeEgRji5pD6agnhccV1Ur1d2DjrFfjuFRQowRLbfYrGtiTReJhH/cDFWQ9bdwIX6/9W8QWxpb/WLl+YpfTZ4MiQ/du8fHeinAksBjnsCYQSaZFH3RwAuewWmaX6HMBMCI30qQELY8+YKwIvbDuN4XSDgVXWZUFfQs8YdsRrU4s4yYc2VmsA643uTX1hDSlItZkS3I9MjQNz0uQudYAJ1Dvu53tYaM3Bupe8rd19RBVLI1DwRpN3Klq8XaRREt+FyYiyPzGHVTFTfg5mvsAWO9MZmT/No176Ple1ZKTQvEXN5k3d/wLCxBqyBEDOkDRkzs7FcbmlSo1NhKn9WAxB/pRkuxUUed2QzFHemzGQYLamVbkMw84X1+kW6XZ'