server:
  port: 8082

spring:
  datasource:
    url: '{cipher}AQATOnIrCagRmSGfeohEsf7Mf1AFa0fsAE2bYWnmKVDBt7GJKZG9Crq9fUmpfiysns6d+ZEP0H8cztw0KOvpsVtGjY6EgGxB+9iKGlNA8iQsq1zvT9vYtPPPS9ArrPMPZx1XUjNaz2BbhJ1qL7SaVHsgHvYL3vJLWwbkwAfgPoXct6AGDRfX3AZCh+QnwJ/aDBtM0ck4nOJDFsQ6MzM4dPUVIPIY1COj9IwtlKlxGn/HmxCT71K+IqanEmNleb0iWhwszm34h79i8m7Qix+V6fB49YK0RJ8EHOygYsqGLj7VXjGydYLYC4fwnnfKvAJ8J0A9HunfcMzBjqCeZab2XJEbK+ru3CAPHguQeQc+YbZn0Nft4peREXiRvA+tbM0HQgeZ93eh6K2bylSRUR3wJi8g15iHRWtmMOtDc5r9aQImzw=='

file:
  storage:
    enabled: true
    bucketName: '{cipher}AQCG8+0RR3/N9KZFBxwvLFWGJUbl3bTeEgRji5pD6agnhccV1Ur1d2DjrFfjuFRQowRLbfYrGtiTReJhH/cDFWQ9bdwIX6/9W8QWxpb/WLl+YpfTZ4MiQ/du8fHeinAksBjnsCYQSaZFH3RwAuewWmaX6HMBMCI30qQELY8+YKwIvbDuN4XSDgVXWZUFfQs8YdsRrU4s4yYc2VmsA643uTX1hDSlItZkS3I9MjQNz0uQudYAJ1Dvu53tYaM3Bupe8rd19RBVLI1DwRpN3Klq8XaRREt+FyYiyPzGHVTFTfg5mvsAWO9MZmT/No176Ple1ZKTQvEXN5k3d/wLCxBqyBEDOkDRkzs7FcbmlSo1NhKn9WAxB/pRkuxUUed2QzFHemzGQYLamVbkMw84X1+kW6XZ'